# Generated by Django 2.1 on 2018-08-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_photo', models.ImageField(height_field=300, upload_to='image/user', width_field=250)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image', models.ImageField(height_field=300, upload_to='image/products', width_field=250)),
                ('product_Image1', models.ImageField(height_field=300, upload_to='image/products', width_field=250)),
                ('product_Image2', models.ImageField(height_field=300, upload_to='image/products', width_field=250)),
                ('product_type', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Photo & Gifts', 'Photo & Gifts'), ('Home Decor', 'Home Decor'), ('Sports', 'Sports'), ('Food', 'Food'), ('etc', 'etc')], default='Nice', max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_cost', models.IntegerField()),
                ('product_sale', models.IntegerField()),
                ('product_rating', models.IntegerField()),
                ('product_in_stock', models.BooleanField(default=True)),
                ('product_description', models.CharField(max_length=500)),
                ('product_wish_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=500)),
                ('shop_type', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Photo & Gifts', 'Photo & Gifts'), ('Home Decor', 'Home Decor'), ('Sports', 'Sports'), ('Food', 'Food'), ('All', 'All')], default='All', max_length=50)),
                ('shop_image', models.ImageField(height_field=300, upload_to='image/shop', width_field=250)),
                ('shop_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('photo', models.ImageField(height_field=300, upload_to='image/shopkeeper', width_field=250)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Shopkeeper'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.PurchaseId'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Consumer'),
        ),
        migrations.AddField(
            model_name='product',
            name='from_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Shop'),
        ),
    ]
