# Generated by Django 2.1 on 2018-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(upload_to='image/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image1',
            field=models.ImageField(upload_to='image/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image2',
            field=models.ImageField(upload_to='image/products'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(upload_to='image/shop'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/shopkeeper'),
        ),
    ]
